# Generated by Django 2.0.10 on 2020-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200428_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=100, verbose_name='客户端')),
                ('score', models.IntegerField(verbose_name='分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '排名',
                'verbose_name_plural': '排名',
                'ordering': ('-score',),
            },
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
